[build]
  command = "npm run build"
  publish = "dist"

# Proxy API requests to your backend 
# This avoids CORS issues by making requests from the same domain

[[redirects]]
  from = "/api/*"
  to = "https://avengers-gym-backend.netlify.app/api/:splat"
  status = 200
  force = true

# This ensures that all routes are directed to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18" 